/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Agent;
import static Klasser.Agent.getConnection;
import Klasser.Alien;
import Klasser.Validering;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author jonat
 */
public class AdminHanteraAgenter extends javax.swing.JFrame {

    private ArrayList<HashMap<String, String>> temp;
// Lägger in 2 knappar i buttongroup, gör att bara en går att klicka på

    public AdminHanteraAgenter() {
        initComponents();
        fyll();

        buttonGroup1.add(jRadKonC);
        buttonGroup1.add(jRadOmrC);
    }
    //Fyller listan med alla områden
    private void fyll() {
        try {
            this.temp = Alien.getDb().fetchRows("Select * from OMRADE");
            System.out.println(this.temp);
            if (temp != null) {
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                int listlagnd = temp.size();
                dtm.setRowCount(listlagnd);

                for (int i = 0; i < temp.size(); i++) {

//                    int currentPlats = Integer.parseInt(Alien.getDb().fetchSingle("Select PLATS from ALIEN"));
//                    int plats = Integer.parseInt(temp.get(i).get("PLATS"));
                    System.out.println(temp.size());
                    String oID = temp.get(i).get("OMRADES_ID");
                    String namn = temp.get(i).get("BENAMNING");
                    ;

                    jTable1.getModel().setValueAt(oID, i, 0);
                    jTable1.getModel().setValueAt(namn, i, 1);

                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLblSokord = new javax.swing.JLabel();
        jTxtSokord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadKonC = new javax.swing.JRadioButton();
        jRadOmrC = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sök efter agent som är chef över kontor eller område");

        jLblSokord.setText("Sökord:");

        jTxtSokord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSokordActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Namn", "Telefon", "Ans.datum", "Admin", "Tillhör område"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRadKonC.setText("Kontorsnamn:");
        jRadKonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadKonCActionPerformed(evt);
            }
        });

        jRadOmrC.setText("Områdes ID:");

        jButton1.setText("Sök");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnExit.setText("Stäng fönster");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadKonC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jRadOmrC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblSokord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtSokord, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtSokord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLblSokord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadKonC)
                    .addComponent(jRadOmrC))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jBtnExit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//@param klick på knappen
//@retur void, skapar en tabell som användaren kan se
// Skapar tabellen och kollar vilken knapp som är itryckt
//Beroende på det söker vi i databasen och fyller tabbellen med svaret och visar användaren    
    private void jTxtSokordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSokordActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            if (jRadKonC.isSelected() && Validering.validName(jTxtSokord.getText())) {

                String sokrad = jTxtSokord.getText();
                temp = Agent.getConnection().fetchRows("SELECT * FROM AGENT WHERE AGENT_ID IN (Select AGENT_ID from KONTORSCHEF where KONTORSBETECKNING= '" + sokrad + "');");

                if (temp != null) {

                    int listlagnd = temp.size();
                    dtm.setRowCount(listlagnd);

                    for (int i = 0; i < temp.size(); i++) {

                        String id = temp.get(i).get("AGENT_ID");
                        String namn = temp.get(i).get("NAMN");
                        String telefon = temp.get(i).get("TELEFON");
                        String ansdat = temp.get(i).get("ANSTALLNINGSDATUM");
                        String admin = temp.get(i).get("ADMINISTRATOR");
                        String omrade = temp.get(i).get("OMRADE");

                        jTable1.getModel().setValueAt(id, i, 0);
                        jTable1.getModel().setValueAt(namn, i, 1);
                        jTable1.getModel().setValueAt(telefon, i, 2);
                        jTable1.getModel().setValueAt(ansdat, i, 3);
                        jTable1.getModel().setValueAt(admin, i, 4);
                        jTable1.getModel().setValueAt(omrade, i, 5);
                    }
                }
            }

            if (jRadOmrC.isSelected() && Validering.isPlats(jTxtSokord.getText())) {

                String sokrad = jTxtSokord.getText();
                temp = getConnection().fetchRows("SELECT * FROM AGENT WHERE AGENT_ID IN (Select AGENT_ID from OMRADESCHEF where OMRADE= '" + sokrad + "');");

                if (temp != null) {

                    int listlagnd = temp.size();
                    dtm.setRowCount(listlagnd);

                    for (int i = 0; i < temp.size(); i++) {

                        String id = temp.get(i).get("AGENT_ID");
                        String namn = temp.get(i).get("NAMN");
                        String telefon = temp.get(i).get("TELEFON");
                        String ansdat = temp.get(i).get("ANSTALLNINGSDATUM");
                        String admin = temp.get(i).get("ADMINISTRATOR");
                        String omrade = temp.get(i).get("OMRADE");

                        jTable1.getModel().setValueAt(id, i, 0);
                        jTable1.getModel().setValueAt(namn, i, 1);
                        jTable1.getModel().setValueAt(telefon, i, 2);
                        jTable1.getModel().setValueAt(ansdat, i, 3);
                        jTable1.getModel().setValueAt(admin, i, 4);
                        jTable1.getModel().setValueAt(omrade, i, 5);
                    }
                }
            }

        } catch (InfException undantag) {
            System.out.print(undantag);
        }

    }//GEN-LAST:event_jTxtSokordActionPerformed

    private void jRadKonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadKonCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadKonCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            if (jRadKonC.isSelected() && Validering.validName(jTxtSokord.getText())) {

                String sokrad = jTxtSokord.getText();
                temp = Agent.getConnection().fetchRows("SELECT * FROM AGENT WHERE AGENT_ID IN (Select AGENT_ID from KONTORSCHEF where KONTORSBETECKNING= '" + sokrad + "');");

                if (temp != null) {

                    int listlagnd = temp.size();
                    dtm.setRowCount(listlagnd);

                    for (int i = 0; i < temp.size(); i++) {

                        String id = temp.get(i).get("AGENT_ID");
                        String namn = temp.get(i).get("NAMN");
                        String telefon = temp.get(i).get("TELEFON");
                        String ansdat = temp.get(i).get("ANSTALLNINGSDATUM");
                        String admin = temp.get(i).get("ADMINISTRATOR");
                        String omrade = temp.get(i).get("OMRADE");

                        jTable1.getModel().setValueAt(id, i, 0);
                        jTable1.getModel().setValueAt(namn, i, 1);
                        jTable1.getModel().setValueAt(telefon, i, 2);
                        jTable1.getModel().setValueAt(ansdat, i, 3);
                        jTable1.getModel().setValueAt(admin, i, 4);
                        jTable1.getModel().setValueAt(omrade, i, 5);
                    }
                }
            }

            if (jRadOmrC.isSelected() && Validering.isPlats(jTxtSokord.getText())) {

                String sokrad = jTxtSokord.getText();
                temp = getConnection().fetchRows("SELECT * FROM AGENT WHERE AGENT_ID IN (Select AGENT_ID from OMRADESCHEF where OMRADE= '" + sokrad + "');");

                if (temp != null) {

                    int listlagnd = temp.size();
                    dtm.setRowCount(listlagnd);

                    for (int i = 0; i < temp.size(); i++) {

                        String id = temp.get(i).get("AGENT_ID");
                        String namn = temp.get(i).get("NAMN");
                        String telefon = temp.get(i).get("TELEFON");
                        String ansdat = temp.get(i).get("ANSTALLNINGSDATUM");
                        String admin = temp.get(i).get("ADMINISTRATOR");
                        String omrade = temp.get(i).get("OMRADE");

                        jTable1.getModel().setValueAt(id, i, 0);
                        jTable1.getModel().setValueAt(namn, i, 1);
                        jTable1.getModel().setValueAt(telefon, i, 2);
                        jTable1.getModel().setValueAt(ansdat, i, 3);
                        jTable1.getModel().setValueAt(admin, i, 4);
                        jTable1.getModel().setValueAt(omrade, i, 5);
                    }
                }
            }

        } catch (InfException undantag) {
            System.out.print(undantag);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
//Stänger fönstret vid klick
    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHanteraAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHanteraAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHanteraAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHanteraAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHanteraAgenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblSokord;
    private javax.swing.JRadioButton jRadKonC;
    private javax.swing.JRadioButton jRadOmrC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtSokord;
    // End of variables declaration//GEN-END:variables
}
