/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Agent;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author jonat
 */
public class AdminFirstPage extends javax.swing.JFrame {

    /**
     * *  Skapar ett Admin start page fönster och hämtar all info om den specifika Agenten som loggat in och gör den till ett objekt
     * med hjälp av metod i Agent klassen, lägger in det objektet i Huvudfönstrets fält agent
     * 
     */
    public AdminFirstPage() {
        initComponents();

        try {
            Agent agent = new Agent(Huvudfonster.agent.getId());
            Huvudfonster.agent = agent;
            jLblAgentNamn.setText(Huvudfonster.agent.getNamn());

        } catch (InfException undantag) {
            JOptionPane.showMessageDialog(null, "Fel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLblAgentNamn = new javax.swing.JLabel();
        jLabelAdmin = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jButtonUtrustning = new javax.swing.JButton();
        jButtonAlienRegister = new javax.swing.JButton();
        jButtonChefer = new javax.swing.JButton();
        jButtonAgenter = new javax.swing.JButton();
        jButtonAndraLosen = new javax.swing.JButton();
        jButtonRegAlien = new javax.swing.JButton();
        jButtonAndraAlien = new javax.swing.JButton();
        jButtonRegAgent = new javax.swing.JButton();
        jButtonTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblAgentNamn.setText("jLabel1");

        jLabelAdmin.setText("Du har admin rättighet");

        jLabelInfo.setText("Välkommen :");

        jButtonUtrustning.setText("Registrera ny utrustning");
        jButtonUtrustning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUtrustningActionPerformed(evt);
            }
        });

        jButtonAlienRegister.setText("Sök på Aliens");
        jButtonAlienRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAlienRegisterActionPerformed(evt);
            }
        });

        jButtonChefer.setText("Sök på Agenter");
        jButtonChefer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCheferActionPerformed(evt);
            }
        });

        jButtonAgenter.setText("Ändra agenter");
        jButtonAgenter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAgenterActionPerformed(evt);
            }
        });

        jButtonAndraLosen.setText("Ändra lösenord");
        jButtonAndraLosen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAndraLosenActionPerformed(evt);
            }
        });

        jButtonRegAlien.setText("Registrera ny Alien");
        jButtonRegAlien.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegAlienActionPerformed(evt);
            }
        });

        jButtonAndraAlien.setText("Ändra alien");
        jButtonAndraAlien.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAndraAlienActionPerformed(evt);
            }
        });

        jButtonRegAgent.setText("Registrera ny Agent");
        jButtonRegAgent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegAgentActionPerformed(evt);
            }
        });

        jButtonTaBort.setText("Ta bort Alien/Utrustning/Agent");
        jButtonTaBort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonRegAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUtrustning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAgenter, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jButtonAndraAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAndraLosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAlienRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonChefer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAgentNamn)
                    .addComponent(jLabelAdmin)
                    .addComponent(jLabelInfo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlienRegister)
                    .addComponent(jButtonChefer))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegAlien)
                    .addComponent(jButtonAndraAlien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegAgent)
                    .addComponent(jButtonAgenter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAndraLosen)
                    .addComponent(jButtonUtrustning))
                .addGap(42, 42, 42)
                .addComponent(jButtonTaBort)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndraLosenActionPerformed
        AndraLosenord fonster = new AndraLosenord();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAndraLosenActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUtrustningActionPerformed
        ReggaNyUtrustning fonster = new ReggaNyUtrustning();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonUtrustningActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAlienRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlienRegisterActionPerformed
        HanteraAliens fonster = new HanteraAliens();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAlienRegisterActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonCheferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheferActionPerformed
        AdminHanteraAgenter fonster = new AdminHanteraAgenter();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonCheferActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAgenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgenterActionPerformed
        AndraAgent fonster = new AndraAgent();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAgenterActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaBortActionPerformed
        TaBort fonster = new TaBort();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonTaBortActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAlienActionPerformed
        ReggaNyAlien fonster = new ReggaNyAlien();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonRegAlienActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAndraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndraAlienActionPerformed
        AndraAlien fonster = new AndraAlien();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAndraAlienActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonRegAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAgentActionPerformed
        ReggaNyAgent fonster = new ReggaNyAgent();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonRegAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenter;
    private javax.swing.JButton jButtonAlienRegister;
    private javax.swing.JButton jButtonAndraAlien;
    private javax.swing.JButton jButtonAndraLosen;
    private javax.swing.JButton jButtonChefer;
    private javax.swing.JButton jButtonRegAgent;
    private javax.swing.JButton jButtonRegAlien;
    private javax.swing.JButton jButtonTaBort;
    private javax.swing.JButton jButtonUtrustning;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLblAgentNamn;
    // End of variables declaration//GEN-END:variables
}
