/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Agent;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author jonat
 */
public class AgentFirstPage extends javax.swing.JFrame {

    /**
     *  Skapar ett Agent start page fönster och hämtar all info om den specifika Agenten som loggat in och gör den till ett objekt
     * med hjälp av metod i Agent klassen, lägger in det objektet i Huvudfönstrets fält agent
     * 
     */
    public AgentFirstPage() {
        initComponents();
        try {

            Agent agent = new Agent(Huvudfonster.agent.getId());
            Huvudfonster.agent = agent;
            jLblAgentNamn.setText(Huvudfonster.agent.getNamn());

        } catch (InfException undantag) {
            System.err.println(undantag);
            System.out.println("mib.grupp2.AgentFirstPage.<init>()");
            JOptionPane.showMessageDialog(null, "Fel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLblInfo = new javax.swing.JLabel();
        jButtonRegUtr = new javax.swing.JButton();
        jButtonRegAlien = new javax.swing.JButton();
        jButtonAndraAlien = new javax.swing.JButton();
        jButtonAndraLosen = new javax.swing.JButton();
        jLblAgentNamn = new javax.swing.JLabel();
        jButtonSokAlien = new javax.swing.JButton();
        jButtonSokChef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblInfo.setText("Välkommen :");

        jButtonRegUtr.setText("Registrera ny Utrustning");
        jButtonRegUtr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegUtrActionPerformed(evt);
            }
        });

        jButtonRegAlien.setText("Registrera Alien");
        jButtonRegAlien.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegAlienActionPerformed(evt);
            }
        });

        jButtonAndraAlien.setText("Ändra alien");
        jButtonAndraAlien.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAndraAlienActionPerformed(evt);
            }
        });

        jButtonAndraLosen.setText("Ändra Lösenord");
        jButtonAndraLosen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAndraLosenActionPerformed(evt);
            }
        });

        jLblAgentNamn.setText("jLabel2");

        jButtonSokAlien.setText("Sök på aliens");
        jButtonSokAlien.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSokAlienActionPerformed(evt);
            }
        });

        jButtonSokChef.setText("Sök på agenter");
        jButtonSokChef.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSokChefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonRegUtr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSokAlien))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonAndraAlien)
                                            .addComponent(jButtonRegAlien))
                                        .addGap(71, 71, 71)
                                        .addComponent(jButtonSokChef))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jButtonAndraLosen)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblInfo)
                    .addComponent(jLblAgentNamn))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegUtr)
                    .addComponent(jButtonSokAlien))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegAlien)
                    .addComponent(jButtonSokChef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAndraAlien)
                    .addComponent(jButtonAndraLosen))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonRegUtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegUtrActionPerformed
        ReggaNyUtrustning fonster = new ReggaNyUtrustning();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonRegUtrActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAlienActionPerformed
        ReggaNyAlien fonster = new ReggaNyAlien();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonRegAlienActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndraLosenActionPerformed
        AndraLosenord fonster = new AndraLosenord();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAndraLosenActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonAndraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndraAlienActionPerformed
        AndraAlien fonster = new AndraAlien();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonAndraAlienActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonSokAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSokAlienActionPerformed
        HanteraAliens fonster = new HanteraAliens();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonSokAlienActionPerformed
//Öppnar nytt fönster vid klick och gör den till fokus.
    private void jButtonSokChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSokChefActionPerformed
        AdminHanteraAgenter fonster = new AdminHanteraAgenter();
        fonster.setVisible(true);
        fonster.requestFocus();
    }//GEN-LAST:event_jButtonSokChefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAndraAlien;
    private javax.swing.JButton jButtonAndraLosen;
    private javax.swing.JButton jButtonRegAlien;
    private javax.swing.JButton jButtonRegUtr;
    private javax.swing.JButton jButtonSokAlien;
    private javax.swing.JButton jButtonSokChef;
    private javax.swing.JLabel jLblAgentNamn;
    private javax.swing.JLabel jLblInfo;
    // End of variables declaration//GEN-END:variables
}
