/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Agent;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import oru.inf.InfException;
import Klasser.Alien;

/**
 *
 * @author jonat
 */
public class AlienStartPage extends javax.swing.JFrame {

    /**
     * Skapar ett Alien start page fönster och hämtar all info om den specifika alien som loggat in och gör den till ett objekt
     * med hjälp av metod i Alien klassen, lägger in det objektet i Huvudfönstrets fält alien
     * kör metoden sqlFragor
     */
    public AlienStartPage() {
        initComponents();

        try {

            Alien alien = new Alien(Huvudfonster.alien.getId());
            Huvudfonster.alien = alien;
            sqlFragor();

        } catch (InfException undantag) {
            System.out.println("mib.grupp2.AlienStartPage.<init>() - " + undantag);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonAndraLosenord = new javax.swing.JButton();
        jLabelValkommen = new javax.swing.JLabel();
        jLabelOmradesPlacering = new javax.swing.JLabel();
        jLabelInfoAgentChef = new javax.swing.JLabel();
        jLabelNamnPaAgent = new javax.swing.JLabel();
        jLabelAgentTelefon = new javax.swing.JLabel();
        jLblNamn = new javax.swing.JLabel();
        jLblPlats = new javax.swing.JLabel();
        jLblNamnAgent = new javax.swing.JLabel();
        jLblTelefon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAndraLosenord.setText("Ändra ditt lösenord");
        jButtonAndraLosenord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAndraLosenordActionPerformed(evt);
            }
        });

        jLabelValkommen.setText("Välkommen Alien :");

        jLabelOmradesPlacering.setText("Du är placerad på plats :");

        jLabelInfoAgentChef.setText("Ditt områdes agentchefs info :");

        jLabelNamnPaAgent.setText("Namn:");

        jLabelAgentTelefon.setText("Telefon:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNamnPaAgent)
                        .addGap(18, 18, 18)
                        .addComponent(jLblNamnAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelOmradesPlacering)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelValkommen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelInfoAgentChef)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAgentTelefon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAndraLosenord)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPlats, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelValkommen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelOmradesPlacering)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInfoAgentChef)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamnPaAgent)
                    .addComponent(jLblNamnAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAgentTelefon)
                    .addComponent(jLblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButtonAndraLosenord)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Öppnar vid klick på knappen ett ändra lösenord fönstret och gör det i fokus
    private void jButtonAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndraLosenordActionPerformed
        AndraLosenord fonster = new AndraLosenord();
        fonster.setVisible(true);
        fonster.requestFocus();

    }//GEN-LAST:event_jButtonAndraLosenordActionPerformed
//Sätter ut diverse information i fönstret som är relevant för den inloggade. Hämtas genom sql eller getters. 
    private void sqlFragor() {
        String namn = Huvudfonster.alien.getNamn();
        String plats = Integer.toString(Huvudfonster.alien.getPlats());

        jLblNamn.setText(namn);
        try {
            jLblPlats.setText(Agent.getConnection().fetchSingle("Select BENAMNING from PLATS where PLATS_ID=" + plats + ";"));
            String namnAgent = Agent.getConnection().fetchSingle("Select NAMN from AGENT where OMRADE IN (Select FINNS_I from PLATS where PLATS_ID =" + plats + " )");
            jLblNamnAgent.setText(namnAgent);
            String telefonAgent = Agent.getConnection().fetchSingle("Select TELEFON from AGENT where OMRADE IN (Select FINNS_I from PLATS where PLATS_ID =" + plats + " )");
            jLblTelefon.setText(telefonAgent);
        } catch (InfException e) {
            System.out.println("fel på frågan");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienStartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAndraLosenord;
    private javax.swing.JLabel jLabelAgentTelefon;
    private javax.swing.JLabel jLabelInfoAgentChef;
    private javax.swing.JLabel jLabelNamnPaAgent;
    private javax.swing.JLabel jLabelOmradesPlacering;
    private javax.swing.JLabel jLabelValkommen;
    private javax.swing.JLabel jLblNamn;
    private javax.swing.JLabel jLblNamnAgent;
    private javax.swing.JLabel jLblPlats;
    private javax.swing.JLabel jLblTelefon;
    // End of variables declaration//GEN-END:variables
}
