/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Validering;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import oru.inf.InfException;
import Klasser.Agent;
import static Klasser.Agent.getConnection;
import Klasser.Alien;
import Klasser.Utrustning;

/**
 *
 * @author vilma
 */
public class ReggaNyUtrustning extends javax.swing.JFrame {

    private Agent agent;
    private int id;
    private Alien alien;
    private ButtonGroup knappGrupp;
    private Utrustning utrustning;

    /**
     * Sätter flera knappar till osynliga
     */
    public ReggaNyUtrustning() {
        initComponents();
        fixaKnappar();

        jLblKal.setVisible(false);
        jTxtKal.setVisible(false);
        jBnReg.setVisible(false);
        jTxtKra.setVisible(false);
        jLblKra.setVisible(false);
        jLblOve.setVisible(false);
        jTxtOve.setVisible(false);

        try {
            String nextId = getConnection().getAutoIncrement("AGENT", "AGENT_ID");
            id = (Integer.parseInt(nextId));
        } catch (InfException e) {
            System.out.println(e);
        }

    }
    //Kollar så att alla rutor är ifyllda korrekt
    private boolean ifyllt() {

        if (Validering.validName(jTxtBen.getText()) && (jCheckKom.isSelected() || jCheckTeknik.isSelected() || jCheckVapen.isSelected())) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och minst en 'checkbox' knapp");
        }
        return false;

    }
    //Skapar buttongroup och lägger till knappar
    private void fixaKnappar() {
        knappGrupp = new ButtonGroup();
        knappGrupp.add(jCheckKom);
        knappGrupp.add(jCheckVapen);
        knappGrupp.add(jCheckTeknik);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKnappGrupp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLblBen = new javax.swing.JLabel();
        jTxtBen = new javax.swing.JTextField();
        jTxtKal = new javax.swing.JTextField();
        jTxtOve = new javax.swing.JTextField();
        jTxtKra = new javax.swing.JTextField();
        jLblKal = new javax.swing.JLabel();
        jLblOve = new javax.swing.JLabel();
        jLblKra = new javax.swing.JLabel();
        jBnReg = new javax.swing.JButton();
        jCheckVapen = new javax.swing.JCheckBox();
        jCheckKom = new javax.swing.JCheckBox();
        jCheckTeknik = new javax.swing.JCheckBox();
        jLblTyp = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jLblINFO = new javax.swing.JLabel();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrera ny utrustning");

        jLblBen.setText("Benämning");

        jTxtBen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBenActionPerformed(evt);
            }
        });

        jTxtKal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKalActionPerformed(evt);
            }
        });

        jTxtOve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtOveActionPerformed(evt);
            }
        });

        jTxtKra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKraActionPerformed(evt);
            }
        });

        jLblKal.setText("Kaliber:");

        jLblOve.setText("Överförningsteknik");

        jLblKra.setText("Kraftkälla");

        jBnReg.setText("Registera");
        jBnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnRegActionPerformed(evt);
            }
        });

        jCheckVapen.setText("Vapen");

        jCheckKom.setText("Kommunikaton");

        jCheckTeknik.setText("Teknik");

        jLblTyp.setText("Typ:");

        jButtonNext.setText("Vidare");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLblINFO.setText("Obs! Tryck på vidare varje gång du uppdaterar något i checkboxarna så du relevant information");

        jBtnExit.setText("Stäng fönster");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblINFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckVapen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblKal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jCheckTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblKra))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jCheckKom)
                                .addGap(176, 176, 176)
                                .addComponent(jLblOve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLblBen)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLblTyp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtKal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtBen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtOve, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtKra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBnReg))))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblINFO)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBen)
                    .addComponent(jTxtBen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblTyp)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtKal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblKal)
                    .addComponent(jCheckVapen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblOve)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckKom)
                        .addComponent(jTxtOve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtKra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblKra)
                    .addComponent(jCheckTeknik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext)
                    .addComponent(jBnReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jBtnExit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtBenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBenActionPerformed

    private void jTxtKalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKalActionPerformed

    private void jTxtOveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtOveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtOveActionPerformed

    private void jTxtKraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKraActionPerformed
/**
 * Om allt är ifyllt korrekt läggs det till det som skrivs läggs utrstninge till
 * i både tabellen för utrstning men också tabellen för den typ av utrstning.
 * Fungerar det att lägga till utrustninga kommer ett pop-uppfönster upp som meddelar.
 * Fungerar det inte att lägga till kommer också ett pop-uppfönster upp.
 * @param evt 
 */
    private void jBnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnRegActionPerformed
        if (ifyllt()) {

            try {
                utrustning = new Utrustning(jTxtBen.getText());

                if (jCheckKom.isSelected()) {
                    if (Validering.validName(jTxtOve.getText())) {
                        getConnection().insert("INSERT INTO KOMMUNIKATION VALUES (" + utrustning.getUtrustingsID() + ",'" + jTxtOve.getText() + "');");
                        utrustning.addUtrustningSql();
                        JOptionPane.showMessageDialog(null, "Utrustningen är registrerad med ID " + id);
                        dispose();
                    }
                } else if (jCheckVapen.isSelected()) {
                    if (Validering.notBlankString(jTxtKal.getText()) && Validering.isDigit(jTxtKal.getText())) {
                        getConnection().insert("INSERT INTO VAPEN VALUES (" + utrustning.getUtrustingsID() + ",'" + jTxtKal.getText() + "');");
                        utrustning.addUtrustningSql();
                        JOptionPane.showMessageDialog(null, "Utrustning är registrerad med ID " + id);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och EN knapp");
                    }

                } else if (jCheckTeknik.isSelected()) {
                    if (Validering.validName(jTxtKra.getText())) {
                        getConnection().insert("INSERT INTO TEKNIK VALUES (" + utrustning.getUtrustingsID() + ",'" + jTxtKra.getText() + "');");
                        utrustning.addUtrustningSql();
                        JOptionPane.showMessageDialog(null, "Utrustning är registrerad med ID " + id);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och EN knapp");
                    }
                }

            } catch (InfException e) {
                System.out.println("fel i sql");
            }
        }
               }//GEN-LAST:event_jBnRegActionPerformed
//visar text och label beroende på vilken knapp som är vald
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if (ifyllt()) {
            if (jCheckVapen.isSelected()) {
                jLblKal.setText("Kaliber:");
                jLblKal.setVisible(true);
                jTxtKal.setVisible(true);
            } else if (!jCheckVapen.isSelected()) {
                jLblKal.setVisible(false);
                jTxtKal.setVisible(false);
            }
            if (jCheckTeknik.isSelected()) {
                jLblKra.setText("Kraftkälla:");
                jLblKra.setVisible(true);
                jTxtKra.setVisible(true);
            } else if (!jCheckTeknik.isSelected()) {
                jLblKra.setVisible(false);
                jTxtKra.setVisible(false);
            }
            if (jCheckKom.isSelected()) {
                jLblOve.setText("Överförningsteknik:");
                jLblOve.setVisible(true);
                jTxtOve.setVisible(true);
            } else if (!jCheckKom.isSelected()) {
                jLblOve.setVisible(false);
                jTxtOve.setVisible(false);

            }
            jBnReg.setVisible(true);
        }

    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReggaNyUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReggaNyUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReggaNyUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReggaNyUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReggaNyUtrustning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnReg;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JCheckBox jCheckKom;
    private javax.swing.JCheckBox jCheckTeknik;
    private javax.swing.JCheckBox jCheckVapen;
    private javax.swing.ButtonGroup jKnappGrupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBen;
    private javax.swing.JLabel jLblINFO;
    private javax.swing.JLabel jLblKal;
    private javax.swing.JLabel jLblKra;
    private javax.swing.JLabel jLblOve;
    private javax.swing.JLabel jLblTyp;
    private javax.swing.JTextField jTxtBen;
    private javax.swing.JTextField jTxtKal;
    private javax.swing.JTextField jTxtKra;
    private javax.swing.JTextField jTxtOve;
    // End of variables declaration//GEN-END:variables
}
