/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Validering;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import Klasser.Agent;
import Klasser.Alien;

/**
 *
 * @author vilma
 */
public class ReggaNyAgent extends javax.swing.JFrame {

    private Agent agent;
    private int id;
    private Alien alien;

    /**
     * Creates new form NewJFrame
     */
    public ReggaNyAgent() {
        initComponents();

        jBtnOk.setVisible(true);

        try {

            String nextId = Alien.getDb().getAutoIncrement("AGENT", "AGENT_ID");
            id = (Integer.parseInt(nextId));

        } catch (InfException undantag) {
            JOptionPane.showMessageDialog(null, "Fel");
        }
    }
    //Kollar om adminknappen är selected eller ej
    private String adminKoll() {
        if (jCheckAdmin.isSelected()) {
            return "J";
        } else {
            return "N";
        }
    }
//Kollar så alla fält är ifyllda
    private boolean ifyllt() {

        if (Validering.validName(jTxtAgnNamn.getText()) && Validering.validPassword(jTxtLosen.getText()) && Validering.validDate(jTxtDate.getText()) && Validering.validName(jTxtOmrade.getText()) && Validering.validTelefon(jTxtTelefon.getText())) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och en 'prick' knapp UNDER admin");
        }
        return false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInfo = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jLblAgnNamn = new javax.swing.JLabel();
        jTxtAgnNamn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLblLosen = new javax.swing.JLabel();
        jTxtLosen = new javax.swing.JTextField();
        jTxtOmrade = new javax.swing.JTextField();
        jLblOmrade = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JTextField();
        jLblTele = new javax.swing.JLabel();
        jTxtTelefon = new javax.swing.JTextField();
        jBtnOk = new javax.swing.JButton();
        jCheckAdmin = new javax.swing.JCheckBox();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInfo.setText("Regga en ny agent");

        jLblDate.setText("Anställningsdatum");

        jLblAgnNamn.setText("Namn:");

        jTxtAgnNamn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtAgnNamnActionPerformed(evt);
            }
        });

        jLblLosen.setText("Lösenord");

        jTxtLosen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtLosenActionPerformed(evt);
            }
        });

        jTxtOmrade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtOmradeActionPerformed(evt);
            }
        });

        jLblOmrade.setText("Områdes namn:");

        jTxtDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtDateActionPerformed(evt);
            }
        });

        jLblTele.setText("Telefonnummer:");

        jTxtTelefon.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtTelefonActionPerformed(evt);
            }
        });

        jBtnOk.setText("Registrera");
        jBtnOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnOkActionPerformed(evt);
            }
        });

        jCheckAdmin.setText("Admin");

        jBtnExit.setText("Stäng fönster");
        jBtnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTxtAgnNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLblLosen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTxtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblAgnNamn))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblTele)
                            .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jInfo)
                .addGap(18, 18, 18)
                .addComponent(jCheckAdmin)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAgnNamn)
                    .addComponent(jLblOmrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgnNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblLosen)
                    .addComponent(jLblTele))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLblDate)
                .addGap(9, 9, 9)
                .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtAgnNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAgnNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAgnNamnActionPerformed

    private void jTxtLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLosenActionPerformed

    private void jTxtOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtOmradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtOmradeActionPerformed

    private void jTxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDateActionPerformed

    private void jTxtTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelefonActionPerformed
/** Om allt är ifyllt korrekt, kollar det så området finns. Finns områrdet skapas
 * agenten och sedan lägger metoden till resten av information i databasen på agenten.
 * Sedan kommer pop-upfönster med om det fungerande eller inte.
 * @param evt 
 */
    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        if (ifyllt()) {
            try {
                String sOmrade = Alien.getDb().fetchSingle("Select OMRADES_ID from OMRADE where BENAMNING ='" + jTxtOmrade.getText() + "';");
                int omrade = Integer.parseInt(sOmrade);
                agent = new Agent(jTxtAgnNamn.getText(), jTxtLosen.getText(), jTxtTelefon.getText(), jTxtDate.getText(), id, omrade, adminKoll());

                Alien.getDb().insert("INSERT INTO AGENT VALUES (" + id + ",'" + agent.getNamn() + "','" + agent.getTelefon() + "','" + agent.getAnstallningsdatum() + "','" + agent.getAdministrator() + "','" + agent.getLosenord() + "'," + agent.getOmrade() + ");");
                Alien.getDb().insert("INSERT INTO FALTAGENT VALUES (" + id + ");");
                JOptionPane.showMessageDialog(null, "Agent är registrerad med ID " + id);
                dispose();

            } catch (InfException e) {
                System.out.println("fel i sql");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Kolla att område är rätt ifyllt, kunde ej hitta ett område med det namnet");
            }
        }
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReggaNyAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JCheckBox jCheckAdmin;
    private javax.swing.JLabel jInfo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblAgnNamn;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblLosen;
    private javax.swing.JLabel jLblOmrade;
    private javax.swing.JLabel jLblTele;
    private javax.swing.JTextField jTxtAgnNamn;
    private javax.swing.JTextField jTxtDate;
    private javax.swing.JTextField jTxtLosen;
    private javax.swing.JTextField jTxtOmrade;
    private javax.swing.JTextField jTxtTelefon;
    // End of variables declaration//GEN-END:variables
}
