/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp2;

import Klasser.Validering;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import oru.inf.InfException;
import Klasser.Agent;
import Klasser.Alien;

/**
 *
 * @author vilmaottner
 */
public class ReggaNyAlien extends javax.swing.JFrame {

    private ButtonGroup knappgrupp;

    private Agent agent;
    private int id;
    private Alien alien;

    /**
     * Initierar och sätter knappar till osynliga
     */
    public ReggaNyAlien() {
        initComponents();
        fixaKnappar();
        jLblRasVal.setVisible(false);
        jTxtRasVal.setVisible(false);
        jBtmReg.setVisible(false);
        try {

            String nextId = Alien.getDb().getAutoIncrement("ALIEN", "ALIEN_ID");
            id = (Integer.parseInt(nextId));

        } catch (InfException undantag) {
            System.out.println("mib.grupp2.ReggaNyAlien.<init>()");
            System.err.println();
        }
    }
    //Skapar en buttongroup av rasknapparna
    private void fixaKnappar() {
        knappGrupp = new ButtonGroup();
        knappGrupp.add(jButtonWorm);
        knappGrupp.add(jButtonBoglodite);
        knappGrupp.add(jButtonSquid);
    }

    //Kollar om det finns en agent som är ansvarig för den alien, om ej ger den fel
    private boolean finnsAgent() {

        try {
            if (Validering.isID(jTxtAnsAge.getText())) {
                int agentId = Integer.parseInt(jTxtAnsAge.getText());
                agent = Agent.getSql(agentId);
                if (agent != null) {

                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Finns ingen agent med de uppgavna uppgifterna");
                    return false;
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Kan ej hitta angiven agent");
        } catch (InfException undantag) {
            JOptionPane.showMessageDialog(null, "Fel i sql");
        }
        return false;
    }

    //Kollar så att allt är ifyllt korrekt
    private boolean ifyllt() {
        int k = Integer.parseInt(jTxtPlats.getText());
        boolean platsKoll = false;
        try {

            if (k < Integer.parseInt(Alien.getDb().getAutoIncrement("PLATS", "PLATS_ID")) && k > 0) {
                platsKoll = true;
            } else {
                JOptionPane.showMessageDialog(null, "Platsen måste vara över 0 och finnas i databasen");
                return platsKoll;

            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Platsen måste vara över 0 och finnas i databasen");

        }

        if (Validering.validName(jTxtNamn.getText()) && Validering.isID(jTxtAnsAge.getText()) && Validering.isPlats(jTxtPlats.getText()) && Validering.validTelefon(jTxtTelNum.getText()) && (jButtonWorm.isSelected() || jButtonSquid.isSelected() || jButtonBoglodite.isSelected()) && platsKoll) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och EN knapp");
        }
        return false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        knappGrupp = new javax.swing.ButtonGroup();
        jLblTitel = new javax.swing.JLabel();
        jTxtAnsAge = new javax.swing.JTextField();
        jLblAnsAge = new javax.swing.JLabel();
        jLblNamn = new javax.swing.JLabel();
        jTxtNamn = new javax.swing.JTextField();
        jLblTelnum = new javax.swing.JLabel();
        jTxtTelNum = new javax.swing.JTextField();
        jLblPlats = new javax.swing.JLabel();
        jTxtPlats = new javax.swing.JTextField();
        jBtmReg = new javax.swing.JButton();
        jLblRas = new javax.swing.JLabel();
        jButtonWorm = new javax.swing.JRadioButton();
        jButtonBoglodite = new javax.swing.JRadioButton();
        jButtonSquid = new javax.swing.JRadioButton();
        jLblRasVal = new javax.swing.JLabel();
        jTxtRasVal = new javax.swing.JTextField();
        jBtnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLblInfo2 = new javax.swing.JLabel();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitel.setText("Registrera en ny alien");

        jLblAnsAge.setText("Ansvarig agent id:");

        jLblNamn.setText("Alien Namn:");

        jTxtNamn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtNamnActionPerformed(evt);
            }
        });

        jLblTelnum.setText("Telefonnummer:");

        jTxtTelNum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtTelNumActionPerformed(evt);
            }
        });

        jLblPlats.setText("Plats id:");

        jBtmReg.setText("Registrera");
        jBtmReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtmRegActionPerformed(evt);
            }
        });

        jLblRas.setText("Ras:");

        jButtonWorm.setText("Worm");

        jButtonBoglodite.setText("Boglodite");

        jButtonSquid.setText("Squid");

        jLblRasVal.setText("jLabel1");

        jBtnNext.setText("Vidare");
        jBtnNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnNextActionPerformed(evt);
            }
        });

        jLabel1.setText("OBS! Tryck på vidare för att uppdatera ädrad info om RAS");

        jLblInfo2.setText("Lösenordet för alien kommer vara \"123\", alien får själv ändra lösenord efteråt.");

        jBtnExit.setText("Stäng fönster");
        jBtnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblRasVal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRasVal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblTelnum)
                            .addComponent(jTxtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPlats)
                            .addComponent(jTxtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNamn)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblRas)
                            .addGap(13, 13, 13)
                            .addComponent(jButtonWorm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonSquid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBoglodite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblInfo2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLblTitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtAnsAge)
                                .addComponent(jLblAnsAge, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addComponent(jBtmReg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitel)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLblInfo2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jLblNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLblPlats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLblTelnum)
                        .addGap(4, 4, 4)
                        .addComponent(jTxtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblAnsAge, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTxtAnsAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnNext)
                        .addGap(18, 18, 18)
                        .addComponent(jBtmReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblRas)
                            .addComponent(jButtonWorm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSquid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBoglodite))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblRasVal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtRasVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnExit))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Använder if-satser för att se vilken knapp som är ifylld.
 * Beroende på vilken knapp som är ifylld kan användaren fylla i olika information.
 * Om det fungerar kommer pop-upfönster upp och om det infe fungerar kommer
 * det också upp felmeddelande.
 * 
 * @param evt 
 */
    private void jBtmRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtmRegActionPerformed
        if (ifyllt() && finnsAgent()) {

            alien = new Alien(jTxtNamn.getText(), "123", jTxtTelNum.getText(), java.time.LocalDate.now().toString(), agent.getId(), Integer.parseInt(jTxtPlats.getText()));
            try {
                alien.setId(id);

                if (jButtonSquid.isSelected()) {
                    if (Validering.notBlankString(jTxtRasVal.getText()) && Validering.isDigit(jTxtRasVal.getText())) {
                        Alien.getDb().insert("INSERT INTO SQUID VALUES (" + id + ",'" + jTxtRasVal.getText() + "');");
                        Alien.getDb().insert("INSERT INTO ALIEN VALUES (" + id + ",'" + alien.getRegistreringsdatum() + "','123','" + alien.getNamn() + "','" + alien.getTelefon() + "'," + alien.getPlats() + "," + alien.getAgent() + ");");
                        JOptionPane.showMessageDialog(null, "Alien är registrerad med ID " +id);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Vänlige  fyll i alla text fält och EN knapp");
                    }
                } else if (jButtonBoglodite.isSelected()) {
                    if (Validering.notBlankString(jTxtRasVal.getText())) {
                        Alien.getDb().insert("INSERT INTO BOGLODITE VALUES (" + id + ",'" + jTxtRasVal.getText() + "');");
                        Alien.getDb().insert("INSERT INTO ALIEN VALUES (" + id + ",'" + alien.getRegistreringsdatum() + "','123','" + alien.getNamn() + "','" + alien.getTelefon() + "'," + alien.getPlats() + "," + alien.getAgent() + ");");
                        JOptionPane.showMessageDialog(null, "Alien är registrerad med ID " + id);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Vänligen fyll i alla text fält och EN knapp");
                    }

                } else if (jButtonWorm.isSelected()) {
                    Alien.getDb().insert("INSERT INTO WORM VALUES (" + id + ");");
                    Alien.getDb().insert("INSERT INTO ALIEN VALUES (" + id + ",'" + alien.getRegistreringsdatum() + "','123','" + alien.getNamn() + "','" + alien.getTelefon() + "'," + alien.getPlats() + "," + alien.getAgent() + ");");
                    JOptionPane.showMessageDialog(null, "Alien är registrerad med ID " + id);
                    dispose();
                }

            } catch (InfException e) {
                System.out.println("fel i sql");
            }
        }


    }//GEN-LAST:event_jBtmRegActionPerformed

    private void jTxtTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelNumActionPerformed

    private void jTxtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNamnActionPerformed
    //Sätter textfält och labels synliga beroende på vilken radiobutton som är vald
    private void jBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextActionPerformed
        if (ifyllt()) {
            if (jButtonSquid.isSelected()) {
                jLblRasVal.setText("Antal Armar :");
                jLblRasVal.setVisible(true);
                jTxtRasVal.setVisible(true);
            } else if (jButtonBoglodite.isSelected()) {
                jLblRasVal.setText("Antal Boogies:");
                jLblRasVal.setVisible(true);
                jTxtRasVal.setVisible(true);
            }
            jBtmReg.setVisible(true);
        }

    }//GEN-LAST:event_jBtnNextActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReggaNyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReggaNyAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtmReg;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JRadioButton jButtonBoglodite;
    private javax.swing.JRadioButton jButtonSquid;
    private javax.swing.JRadioButton jButtonWorm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAnsAge;
    private javax.swing.JLabel jLblInfo2;
    private javax.swing.JLabel jLblNamn;
    private javax.swing.JLabel jLblPlats;
    private javax.swing.JLabel jLblRas;
    private javax.swing.JLabel jLblRasVal;
    private javax.swing.JLabel jLblTelnum;
    private javax.swing.JLabel jLblTitel;
    private javax.swing.JTextField jTxtAnsAge;
    private javax.swing.JTextField jTxtNamn;
    private javax.swing.JTextField jTxtPlats;
    private javax.swing.JTextField jTxtRasVal;
    private javax.swing.JTextField jTxtTelNum;
    private javax.swing.ButtonGroup knappGrupp;
    // End of variables declaration//GEN-END:variables
}
